# https://ishida-it.com/blog/post/2019-11-21-docker-nodejs/
version: '3'
services:
  app:
    image: node:12
    environment:
      - DEBUG=app:*
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./booklog:/app
    working_dir: /app
    command: node app.js